// Prospectos multi-fuente del ICP de Siemon (YouTube + Instagram), 2026-07-07.
export default [
{
"nombre": "Motivación personal y paz mental.",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UCt9zQU8qubtPSbjG7tZi9xg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCt9zQU8qubtPSbjG7tZi9xg",
"facebook": "https://facebook.com/profile.php"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 92,
"problemas": [
"4,630 subs",
"outlier 65043",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 92/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 4630,
"outlier": 65043,
"fit": 92,
"bio": "Emprende un viaje inspirador hacia el éxito y la realización personal. Enfrenta cada día con determinación, el éxito es el resultado de un compromiso constante y la pasión por lo que haces. Cultiva la confianza en ti mismo y en tus habilidades, mantén tu entusiasmo a pesar de las dificultades, y recuerda que el cambio es la única constante en la vida. No permitas que el miedo te detenga; en su lug",
"seguidores": 4630,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2025-03-29",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Forever Freedom",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "",
"web": "https://www.youtube.com/channel/UCaLEuYEaDBfqD0hR7-pLo5A",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCaLEuYEaDBfqD0hR7-pLo5A"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 88,
"problemas": [
"3,860 subs",
"outlier 13293",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 88/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 3860,
"outlier": 13293,
"fit": 88,
"bio": "¡Bienvenidos a Forever Freedom! En este canal encontraran contenido relacionado con emprendimientos, finanzas, negocios y sobre todo... ¡Los mejores consejos de los mejores Empresarios!\n\n¡¡¡Suscribete para MAS CONTENIDO de VALOR como este!!!\n\n\n",
"seguidores": 3860,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-03-20",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Luis M. Villanueva",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "",
"web": "https://www.youtube.com/channel/UCe57OrtUiB1ji2ilK9NBqkg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCe57OrtUiB1ji2ilK9NBqkg",
"instagram": "https://www.instagram.com/lu1sma/",
"instagram_handle": "@lu1sma",
"tiktok": "https://www.tiktok.com/@lu1sma",
"tiktok_handle": "@lu1sma",
"linkedin": "https://www.linkedin.com/in/luismvill/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 85,
"problemas": [
"48,900 subs",
"outlier 2130",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 85/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 48900,
"outlier": 2130,
"fit": 85,
"bio": "Hace 10 años aproximadamente comenzó mi andadura de forma profesional en el mundo de Internet, mas concretamente en el mundo del SEO.\n\nY hace 8 años empecé este canal de YouTube con el objetivo de compartir algunas de las técnicas y estrategias de SEO que mas resultados me daban en las marcas con las que trabajaba.\n\nHoy, tras estos 8 años , y después de convertir este canal en una referencia en el",
"seguidores": 48900,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-06-09",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "EmprendeMax",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCaq9YJD8Tubqz1cNNe8dmlg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCaq9YJD8Tubqz1cNNe8dmlg"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 85,
"problemas": [
"41,700 subs",
"outlier 16309",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 85/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 41700,
"outlier": 16309,
"fit": 85,
"bio": "Hola y bienvenid@ a EmprendeMax! \n\n¡Tu canal definitivo para desbloquear el potencial financiero y empresarial! Si estás buscando consejos sobre cómo administrar tus finanzas, hacer crecer tu negocio y alcanzar la libertad financiera, ¡has llegado al lugar indicado! En EmprendeMax, exploramos una amplia gama de temas relacionados con las finanzas personales, estrategias de inversión, gestión empre",
"seguidores": 41700,
"pais": "US",
"enlaces": [],
"ultima_pub": "2026-07-05",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Finanzas con Ross",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCurHnbQ-zuAcStP82vHB1Gw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCurHnbQ-zuAcStP82vHB1Gw",
"instagram": "https://www.instagram.com/planifiquemosfinanzas/",
"instagram_handle": "@planifiquemosfinanzas",
"tiktok": "https://www.tiktok.com/@planifiquemosfinanzas",
"tiktok_handle": "@planifiquemosfinanzas",
"facebook": "https://facebook.com/planifiquemosfinanzas"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 84,
"problemas": [
"36,300 subs",
"outlier 5938",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 84/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 36300,
"outlier": 5938,
"fit": 84,
"bio": "Te apoyo en lograr Finanzas Saludables\nConsejos y Tips\n📌 Motivación\n📌 Coaching financiero\n📌 Tutoriales\n📌 Talleres, cursos y más\n",
"seguidores": 36300,
"pais": "US",
"enlaces": [],
"ultima_pub": "2026-07-01",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "converzzo",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "CO",
"web": "https://www.youtube.com/channel/UCmIlY59NzX3Z18-PwUzLD1g",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCmIlY59NzX3Z18-PwUzLD1g",
"instagram": "https://www.instagram.com/converzzo/",
"instagram_handle": "@converzzo",
"tiktok": "https://www.tiktok.com/@converzzo",
"tiktok_handle": "@converzzo",
"linkedin": "https://www.linkedin.com/company/converzzo/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 84,
"problemas": [
"44,400 subs",
"outlier 425",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 84/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 44400,
"outlier": 425,
"fit": 84,
"bio": "🎯 Aprende de marketing digital, contenido para redes sociales y estrategias de venta online\nEn Converzzo te enseñamos a crear contenido estratégico que conecta con tu audiencia y convierte seguidores en clientes.\n\n",
"seguidores": 44400,
"pais": "CO",
"enlaces": [],
"ultima_pub": "2026-07-02",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "ADN Financiero",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "",
"web": "https://www.youtube.com/channel/UCGsIqLkK3RSQtx6tvNWnZxw",
"telefono": "",
"email": "adn.financiero.contactos@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCGsIqLkK3RSQtx6tvNWnZxw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 83,
"problemas": [
"119,000 subs",
"outlier 2487",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 83/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 119000,
"outlier": 2487,
"fit": 83,
"bio": "¡Bienvenido a esta comunicad! En este canal se comparten enseñanzas, estrategias y los mejores hábitos relacionadas a las finanzas, crecimiento y desarrollo personal. El objetivo es ayudarte a alcanzar tu máximo potencial en el manejo de tu dinero y que este se convierta en tu aliado. “Recuerda, el dinero es un excelente esclavo, pero un pésimo amo”; por ello, es importante aprender finanzas perso",
"seguidores": 119000,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-05-21",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Wayo Castellanos",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UC4Nq_1UMIhTTlZ8HhUxEM2g",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UC4Nq_1UMIhTTlZ8HhUxEM2g"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 83,
"problemas": [
"163,000 subs",
"outlier 19973",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 83/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 163000,
"outlier": 19973,
"fit": 83,
"bio": "Empieza a invertir hoy mismo🔥\n\nhttps://beacons.ai/wayocastellanos?utm_source=ig&utm_medium=social&utm_content=link_in_bio",
"seguidores": 163000,
"pais": "MX",
"enlaces": [
"https://beacons.ai/wayocastellanos?utm_source=ig&utm_medium=social&utm_content=link_in_bio"
],
"ultima_pub": "2026-07-05",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Maria Prieto ",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCLLCpPQK3Q0GV93UKzfiiyQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCLLCpPQK3Q0GV93UKzfiiyQ",
"instagram": "https://www.instagram.com/mariaprieto.../",
"instagram_handle": "@mariaprieto...",
"tiktok": "https://www.tiktok.com/@maria",
"tiktok_handle": "@maria",
"facebook": "https://facebook.com/mariaprietoofical"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 83,
"problemas": [
"76,100 subs",
"outlier 1066",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 83/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 76100,
"outlier": 1066,
"fit": 83,
"bio": "Descubre 100% GRATIS Como te podemos ayudar a Monetizar tus redes sociales convirtiendose en influencer afiliada certificada trabajando desde tu casa a un click de tu celular  👉  https://mujeresconpoder.com/youtube\n\n👋 Me llamo María Prieto.\n🇨🇴 Soy colombiana y esta es mi historia de cómo pasé de tener anemia, desórdenes alimenticios, baja autoestima y solo $30 dólares en mi cuenta bancaria a los 2",
"seguidores": 76100,
"pais": "US",
"enlaces": [
"https://mujeresconpoder.com/youtube"
],
"ultima_pub": "2026-07-07",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Better Wallet en Español",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "PE",
"web": "https://www.youtube.com/channel/UCZWDHbpDetLUj5SgOZFvWhw",
"telefono": "",
"email": "betterwallet.contact@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCZWDHbpDetLUj5SgOZFvWhw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 83,
"problemas": [
"88,300 subs",
"outlier 6148",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 83/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 88300,
"outlier": 6148,
"fit": 83,
"bio": "Bienvenido a Better Wallet! \n\nEn este canal nuestra meta es ayudarte y brindarte información educativa acerca de temas relacionados a inversiones, finanzas personales, ahorros y mucho más.\n\nAquí podrás adquirir los conocimientos que necesitas para mejorar la gestión de tu dinero y alcanzar tus metas financieras.\n\nSi estas interesado en aprender más sobre estos temas, asegúrate de darle al botón de",
"seguidores": 88300,
"pais": "PE",
"enlaces": [],
"ultima_pub": "2026-07-01",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Just Lessons",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "",
"web": "https://www.youtube.com/channel/UCJ-NnBDvL867WGtNzPT5lLA",
"telefono": "",
"email": "nithproject6@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCJ-NnBDvL867WGtNzPT5lLA"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 82,
"problemas": [
"155,000 subs",
"outlier 2701",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 82/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 155000,
"outlier": 2701,
"fit": 82,
"bio": "consejos de ayuda, disciplina, mente, fortaleza. Encuentra tu mejor versión, apoya tu crecimiento personal, recibe consejos y herramientas para ser mas disciplinado, dejar la pereza y convertirte en alguien exitoso.\n\nCanal NO OFICIAL inspirado en las enseñanzas de el gran Brian Tracy\n\n\n👀AVISO DE CONTENIDO👀\n\nEste canal NO es oficial de Brian Tracy, por ello se agregan advertencias al video. Nuestro",
"seguidores": 155000,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Hábito Emprendedor",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "CO",
"web": "https://www.youtube.com/channel/UCRUp9_7qdkB0YLgpC599-Rw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCRUp9_7qdkB0YLgpC599-Rw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 80,
"problemas": [
"174,000 subs",
"outlier 1725",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 80/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 174000,
"outlier": 1725,
"fit": 80,
"bio": "El Hábito del Emprendedor es un canal donde se comparten estrategias para mejorar los hábitos financieros de todas las personas. En este espacio se comparten generalidades de las finanzas. Además, se presenta una guía basada en hechos personales sobre el manejo adecuado del dinero, con el objetivo de compartir las experiencias financieras de nuestro día a día. Bienvenido a esta comunidad de empren",
"seguidores": 174000,
"pais": "CO",
"enlaces": [],
"ultima_pub": "2026-07-02",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Velocity Media",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCJZzvHlREiRe1uwr10GrNhQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCJZzvHlREiRe1uwr10GrNhQ"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 80,
"problemas": [
"167,000 subs",
"outlier 837",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 80/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 167000,
"outlier": 837,
"fit": 80,
"bio": "Velocity es la plataforma premium de marketing y emprendimiento en habla hispana. En 10–15 minutos al día accedes a series tipo documental, podcasts en cápsulas y formaciones diseñadas para impulsar tu negocio con ideas claras, accionables y con alta calidad de producción. \n\nUna sola suscripción, una biblioteca completa y una experiencia tan cuidada como las mejores plataformas de streaming. Cread",
"seguidores": 167000,
"pais": "ES",
"enlaces": [
"https://velocitymedia.info/yt/canal"
],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Actitud Millonaria - Josue Peña",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCdRuuenOZ4zoVwT-IJsRMTA",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCdRuuenOZ4zoVwT-IJsRMTA",
"instagram": "https://www.instagram.com/yojosuepena/",
"instagram_handle": "@yojosuepena",
"twitter": "https://twitter.com/itsjosuepena",
"linkedin": "https://www.linkedin.com/in/itsjosuepena/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 77,
"problemas": [
"409,000 subs",
"outlier 742",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 77/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 409000,
"outlier": 742,
"fit": 77,
"bio": "Descubre Como Estamos Ayudando A Personas Como TU, A Ganar $10,000 USD Mensuales convirtiéndose en un Emprendedor o Vendedor Digital, Sin tener seguidores y Sin crear un negocio desde cero 👉 https://closerdigital.net/10k/youtubebio\n\n",
"seguidores": 409000,
"pais": "US",
"enlaces": [
"https://closerdigital.net/10k/youtubebio"
],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "maxmaxdata",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UC0nvCwGLmrKFZ6phJ19BoYQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UC0nvCwGLmrKFZ6phJ19BoYQ"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 77,
"problemas": [
"451,000 subs",
"outlier 4497",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 77/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 451000,
"outlier": 4497,
"fit": 77,
"bio": "¡SUSCRÍBETE para aprender e informarte de INTELIGENCIA ARTIFICIAL y BIG DATA!\n\nSoy Pablo Álvarez Azcúnaga, CEO de mmd, Consultor de Data y Profesor Universitario.\nHe empezado en marzo 2024 con mi marca personal, y me ayudas apoyando mi contenido. Muchas gracias :)\n\nPODCAST: La Nueva Normalidata - Entrevistas, Actualidad, Anécdotas.\n",
"seguidores": 451000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Adrià Solà Pastor",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCvzk_MwdXD6jQa4Se-6B9ZQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCvzk_MwdXD6jQa4Se-6B9ZQ",
"instagram": "https://www.instagram.com/adriasolapastor/",
"instagram_handle": "@adriasolapastor"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 77,
"problemas": [
"1,860,000 subs",
"outlier 524",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 77/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 1860000,
"outlier": 524,
"fit": 77,
"bio": "Soy Adrià Solà Pastor. Un hombre apasionado por la educación, el emprendimiento y la comunicación.\n\nMe formé en Ciencias Políticas, Filosofía y Derecho en La Sorbona (París) y Columbia University (NYC).\n\nLlevo una década enseñando e implementando la comunicación como palanca para transformar la vida personal, profesional, relacional y financiera de personas y empresas.\n\nLo que hemos construido: \n\n",
"seguidores": 1860000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-05",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "PRODUCTIVIDAD JAPONESA",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCvwWZtTAH7h9DA8LNGOIt5w",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCvwWZtTAH7h9DA8LNGOIt5w"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 77,
"problemas": [
"12,500 subs",
"outlier 186",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 77/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 12500,
"outlier": 186,
"fit": 77,
"bio": "PRODUCTIVIDAD JAPONESA — Este es un espacio para quienes buscan una productividad real basada en la psicología japonesa. Mi misión es ayudarte a superar la fatiga mental y dominar tu gestión del tiempo mediante el minimalismo japonés y la mentalidad japonesa aplicada al éxito.\n\nAquí aprenderás a diseñar una rutina japonesa de alto impacto. Nos enfocamos en:\n\n✔️ Método japonés y Kaizen diario: Pequ",
"seguidores": 12500,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "ERA DIGITAL",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "",
"web": "https://www.youtube.com/channel/UC9Wy7iw5GzWRFfSD4NNq1eA",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UC9Wy7iw5GzWRFfSD4NNq1eA"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 77,
"problemas": [
"154,000 subs",
"outlier 6211",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 77/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 154000,
"outlier": 6211,
"fit": 77,
"bio": "Conversaciones sobre emprendimiento y negocios con Fundadores, CEO´s y Expertos.",
"seguidores": 154000,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-07-05",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Uri Sabat",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCfJYyfonhgqd3Pwbx_df4Zw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCfJYyfonhgqd3Pwbx_df4Zw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 76,
"problemas": [
"1,230,000 subs",
"outlier 4762",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 76/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 1230000,
"outlier": 4762,
"fit": 76,
"bio": "El 64 % de la gente que ve este vídeo no está suscrita. Si te gusta el contenido, revisa si estás suscrito y dale al botón. ¡Gracias!\n",
"seguidores": 1230000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Margarita Pasos",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCQjnzUXqISD6dfQTrX0bzoQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCQjnzUXqISD6dfQTrX0bzoQ"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 75,
"problemas": [
"1,030,000 subs",
"outlier 1408",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 75/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 1030000,
"outlier": 1408,
"fit": 75,
"bio": "✨ ¡Hola! Soy Margarita Pasos, y en este canal te ayudo a desbloquear tu máximo potencial. 🚀 Encuentra videos sobre Dinero, inteligencia emocional, liderazgo, ventas y mucho más que te llevarán al siguiente nivel. Con más de 20 años de experiencia entrenando empresas pequeñas, medianas y Fortune 500, mi misión es ayudar a los emprendedores del mundo a vivir una vida fantástica y abundante, emociona",
"seguidores": 1030000,
"pais": "US",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "De la Mano Con Jinna",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCVBfUB1lo9hMP8pf6gJlY5A",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCVBfUB1lo9hMP8pf6gJlY5A"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 75,
"problemas": [
"31,600 subs",
"outlier 18635",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 75/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 31600,
"outlier": 18635,
"fit": 75,
"bio": "",
"seguidores": 31600,
"pais": "US",
"enlaces": [],
"ultima_pub": "2026-07-07",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Emprende Aprendiendo",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "",
"web": "https://www.youtube.com/channel/UCyM-2pRapEv6V2q7UNO9icg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCyM-2pRapEv6V2q7UNO9icg"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 74,
"problemas": [
"2,270,000 subs",
"outlier 561",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 74/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 2270000,
"outlier": 561,
"fit": 74,
"bio": "💡¿Alguna vez te has preguntado cómo Facebook, Zara o Coca Cola se han vuelto tan grandes? ¿Cómo nos influencian estas empresas? ¿Y qué puedes aprender de ellas? ¡Bienvenido a Emprende Aprendiendo!\n\nEste es el canal de empresa y marketing donde personas como tú vienen a aprender cada día sobre cómo montar una compañía, aumentar tus ventas y llevar tus ideas y productos a otro nivel. Somos emprended",
"seguidores": 2270000,
"pais": "",
"enlaces": [],
"ultima_pub": "2026-06-23",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "ExpHub - Prashant Kirad",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "IN",
"web": "https://www.youtube.com/channel/UCgoyBmLOMNWmsiVkj-MezyQ",
"telefono": "",
"email": "exphubdelhi@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCgoyBmLOMNWmsiVkj-MezyQ",
"instagram": "https://www.instagram.com/prashant_.kirad.../",
"instagram_handle": "@prashant_.kirad...",
"twitter": "https://twitter.com/Prashantkirad09",
"facebook": "https://facebook.com/KiradPrashant",
"linkedin": "https://www.linkedin.com/in/prashant-kirad/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 74,
"problemas": [
"12,000,000 subs",
"outlier 316",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 74/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 12000000,
"outlier": 316,
"fit": 74,
"bio": "Hey everyone!\n\nThis is Prashant, Mentor of 10 Lakh+ Students and also I have Cracked IIT-JEE examination in my First attempt\n\nThis channel is all about :\n- Motivational videos\n- Guidance and strategy\n- Helping Students to achieve goals\n- My life inspiring Stories\n\n\nMy aim is to help each and every student with free and quality education in India.\n\nFor businesses enquiry \nMail  :  exphubdelhi@gmail",
"seguidores": 12000000,
"pais": "IN",
"enlaces": [],
"ultima_pub": "2026-06-23",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "El Club de Inversión",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCtWEGc5ws4HvMvCW-hVY-Gw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCtWEGc5ws4HvMvCW-hVY-Gw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 74,
"problemas": [
"346,000 subs",
"outlier 485",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 74/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 346000,
"outlier": 485,
"fit": 74,
"bio": "En el canal de El Club de Inversión, comparto contigo las formas más rentables para ganar más dinero gracias a la inversión en bolsa, en inmobiliario, en criptomonedas y en muchas otras inversiones alternativas.\n\nMejorarás tu educación financiera y aprenderás a generar plusvalías e ingresos pasivos conociendo las mejores estrategias de inversión.\n\nInicia tu camino hacia una situación económica muc",
"seguidores": 346000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Pro Web Design",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UCko2RWyofvqp3wt-2YNPyWw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCko2RWyofvqp3wt-2YNPyWw",
"facebook": "https://facebook.com/prowebdesignmarketing"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 73,
"problemas": [
"24 subs",
"outlier 1389",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 73/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 24,
"outlier": 1389,
"fit": 73,
"bio": "Hacemos lo que más nos gusta. ¡La creatividad nos divierte!\nNos encanta nuestro trabajo y disfrutamos de cada nuevo proyecto que realizamos, como si fuera nuestro.\n\nTrabajamos en diseño de web y diseño gráfico desde el 2002, fuimos incorporando nuevas formas de marketing digital y creación de contenido en video, para incorporarlas en tus sitios web y redes sociales, para que tu negocio pueda llega",
"seguidores": 24,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-05-08",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Daniel Penin",
"fuente": "youtube",
"categoria": "YouTuber · emprendimiento digital",
"ciudad": "BR",
"web": "https://www.youtube.com/channel/UCXQPvU8tGvWy_mAfPPav--Q",
"telefono": "",
"email": "ndanielgonzagatj@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCXQPvU8tGvWy_mAfPPav--Q",
"instagram": "https://www.instagram.com/danielpenin/",
"instagram_handle": "@danielpenin",
"tiktok": "https://www.tiktok.com/@danpenin",
"tiktok_handle": "@danpenin",
"twitter": "https://twitter.com/peninoficial"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 73,
"problemas": [
"2,640,000 subs",
"outlier 409",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 73/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 2640000,
"outlier": 409,
"fit": 73,
"bio": "Marketing, Economia, Negócios, Empreendedorismo, Crescimento Pessoal, Investimentos e de vez em quando uns Documentários. \n\n-----------------------\n\nTelegram exclusivo:\nhttps://t.me/DanielPenin\n\nWHATSAPP ATENDIMENTO EXCLUSIVO\n https://api.whatsapp.com/send/?phone=5537991191731\n\n\n-----------------------\n\n",
"seguidores": 2640000,
"pais": "BR",
"enlaces": [
"https://t.me/DanielPenin",
"https://api.whatsapp.com/send/?phone=5537991191731"
],
"ultima_pub": "2026-06-27",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Aprendamos Marketing",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UChq0O-Nb05OrWPglKV5w4bg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UChq0O-Nb05OrWPglKV5w4bg",
"instagram": "https://www.instagram.com/aprendamosmarketing/",
"instagram_handle": "@aprendamosmarketing",
"facebook": "https://facebook.com/AprendamosMarketing"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 73,
"problemas": [
"672,000 subs",
"outlier 674",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 73/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 672000,
"outlier": 674,
"fit": 73,
"bio": "Simplificando el marketing digital para que tu negocio venda más. \nAumenta tus ventas con herramientas y estrategias  de una forma sencilla y práctica.\n\n",
"seguidores": 672000,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-07-07",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "HACKEANDO LA MENTE ",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "JP",
"web": "https://www.youtube.com/channel/UCAw9tjiXS31HRBAXiD5TlVg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCAw9tjiXS31HRBAXiD5TlVg"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 73,
"problemas": [
"87,400 subs",
"outlier 687",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 73/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 87400,
"outlier": 687,
"fit": 73,
"bio": "Aquí no vas a encontrar motivación vacía.\n\nVas a encontrar cosas que tal vez ya sentías… pero nunca supiste explicar.\n\nEste canal trata sobre la mente — no la parte obvia, sino esa parte silenciosa que influye en tus decisiones, tus hábitos y en todo lo que evitas ver.\n\nAlgunos videos te harán pensar.\nOtros te van a incomodar.\nY algunos… van a sentirse como si fueran hechos exactamente para ti.\n\nS",
"seguidores": 87400,
"pais": "JP",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "DIBUJANDO EL ÉXITO ",
"fuente": "youtube",
"categoria": "YouTuber · libertad financiera",
"ciudad": "BR",
"web": "https://www.youtube.com/channel/UCjZcJUfflZmafZYIC3R63rw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCjZcJUfflZmafZYIC3R63rw"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 73,
"problemas": [
"77,700 subs",
"outlier 1025",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 73/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 77700,
"outlier": 1025,
"fit": 73,
"bio": "¡Hola a todos!  Bienvenidos, soy el creador de los videos que ves aquí. Quiero compartir un poco de mi historia: comencé a ver videos motivacionales cuando pasaba por un momento difícil de depresión. Esos videos fueron esenciales para ayudarme a superar esa etapa y me dieron el valor para iniciar mi propio camino. Comencé vendiendo verduras en mi ciudad natal y, más tarde, pasé a vender pan.\n\nInsp",
"seguidores": 77700,
"pais": "BR",
"enlaces": [],
"ultima_pub": "2026-06-13",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "EDteam",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "PE",
"web": "https://www.youtube.com/channel/UCP15FVAA2UL-QOcGhy7-ezA",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCP15FVAA2UL-QOcGhy7-ezA",
"instagram": "https://www.instagram.com/edteamlat/",
"instagram_handle": "@edteamlat",
"tiktok": "https://www.tiktok.com/@edteam",
"tiktok_handle": "@edteam"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 72,
"problemas": [
"992,000 subs",
"outlier 1448",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 72/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 992000,
"outlier": 1448,
"fit": 72,
"bio": "🚀 ¡Llegó el fin de semana más esperado del año! Hasta 50% de descuento para aprender Programación e Inteligencia Artificial durante el EDweekend 2026.\n",
"seguidores": 992000,
"pais": "PE",
"enlaces": [],
"ultima_pub": "2026-07-03",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "The Wild Project",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCBYyJBCtCvgqA4NwtoPMwpQ",
"telefono": "",
"email": "invitados@jordiwild.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCBYyJBCtCvgqA4NwtoPMwpQ",
"facebook": "https://www.facebook.com/TheWildProjectOficial",
"instagram": "https://www.instagram.com/jordiwild8/",
"instagram_handle": "@jordiwild8",
"twitter": "https://twitter.com/JordiWild",
"tiktok": "https://www.tiktok.com/@jordiwild",
"tiktok_handle": "@jordiwild"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 72,
"problemas": [
"7,250,000 subs",
"outlier 381",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 72/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 7250000,
"outlier": 381,
"fit": 72,
"bio": "CADA MARTES Y JUEVES NUEVOS EPISODIOS.\nBienvenidos a THE WILD PROJECT, el podcast de Jordi Wild. Charlas con los invitados más interesantes, actualidad, ciencia, deportes, filosofía, psicología, misterio, debates y tertulias... y muchísimo más. Cada semana hablando alto y claro sobre el mundo que nos rodea. ¡No te lo pierdas!\n\nAdemás de Youtube, sigue el podcast cada semana desde:\n🔊 Suscríbete a P",
"seguidores": 7250000,
"pais": "ES",
"enlaces": [
"https://podimo.es/thewildproject",
"https://www.facebook.com/TheWildProjectOficial",
"https://www.instagram.com/jordiwild8/",
"https://twitter.com/JordiWild",
"https://www.facebook.com/JordiWild"
],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Andres Garza",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UCSUwTmHIP_rlCTZeQW2oiEg",
"telefono": "",
"email": "talento@andresgarzam.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCSUwTmHIP_rlCTZeQW2oiEg",
"instagram": "https://www.instagram.com/andresgarzam/",
"instagram_handle": "@andresgarzam",
"tiktok": "https://www.tiktok.com/@capital_intel...",
"tiktok_handle": "@capital_intel...",
"twitter": "https://twitter.com/andresgarzam",
"facebook": "https://facebook.com/AndresGrzM",
"linkedin": "https://www.linkedin.com/in/andresgar/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 71,
"problemas": [
"5,440,000 subs",
"outlier 586",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 71/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 5440000,
"outlier": 586,
"fit": 71,
"bio": "Lic. en Administración Financiera.\nAsesor en Estrategias De Inversión Certificado (AMIB Figura 3).\n",
"seguidores": 5440000,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-07-07",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Productividad Real",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCkDzQUmoUKjoNIyWpPYaVLQ",
"telefono": "",
"email": "colaboraproductividadreal@gmail.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCkDzQUmoUKjoNIyWpPYaVLQ",
"instagram": "https://www.instagram.com/productividadreal1/",
"instagram_handle": "@productividadreal1",
"tiktok": "https://www.tiktok.com/@productividadreal1",
"tiktok_handle": "@productividadreal1"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 71,
"problemas": [
"82,600 subs",
"outlier 2886",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 71/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 82600,
"outlier": 2886,
"fit": 71,
"bio": "Japón lleva siglos resolviendo lo que Occidente no sabe ni nombrar: cómo dormir menos y rendir más, cómo aprender sin esfuerzo, cómo trabajar sin quemarte, cómo vivir sin ansiedad.\n\nEn este canal traducimos esa sabiduría a tu vida real. Sin filosofía abstracta. Sin motivación vacía. Solo lo que funciona.\n\n🎌 Nuevo vídeo cada semana\n📥 Sistema de organización gratuito → https://soyproductividadreal.c",
"seguidores": 82600,
"pais": "ES",
"enlaces": [
"https://soyproductividadreal.com"
],
"ultima_pub": "2026-07-02",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Moris Dieck | Finanzas e Inversiones ",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UCxFACDJ98idvo9Gq9M9AQgg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCxFACDJ98idvo9Gq9M9AQgg",
"instagram": "https://www.instagram.com/morisdieck/",
"instagram_handle": "@morisdieck",
"tiktok": "https://www.tiktok.com/@morisdieck",
"tiktok_handle": "@morisdieck",
"twitter": "https://twitter.com/morisdieck",
"facebook": "https://facebook.com/morisdieck",
"linkedin": "https://www.linkedin.com/in/morisdieck/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 70,
"problemas": [
"901,000 subs",
"outlier 648",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 70/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 901000,
"outlier": 648,
"fit": 70,
"bio": "¡Tu nueva vida financiera empieza aquí! Moris Dieck es un visionario financiero y consultor de negocios. Es un firme creyente de que la educación e inclusión financiera son pilares fundamentales para el desarrollo y crecimiento de cualquier sociedad. Durante su carrera, ha ayudado a personas a mejorar su vida financiera y a empresas a alcanzar sus objetivos.\n\nMoris emprendió un movimiento educativ",
"seguidores": 901000,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Financial Mentors TV - Español",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "US",
"web": "https://www.youtube.com/channel/UCAqatD5Kmib2qQ1OIVC5_nQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCAqatD5Kmib2qQ1OIVC5_nQ",
"twitter": "https://twitter.com/FinancialMenTV",
"facebook": "https://facebook.com/FinancialMentorsES"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 70,
"problemas": [
"3,200,000 subs",
"outlier 1859",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 70/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 3200000,
"outlier": 1859,
"fit": 70,
"bio": "Creamos este Canal Youtube con el fin de desarrollar conocimientos, actitudes y prácticas financieras accesibles en Idioma Español.\nLa misión del Equipo Financial Mentors - Español es la de acercarte la Educación Financiera de la manera que consideramos más adecuada: fácil, sencilla y práctica.\n\nSi quieres hacernos alguna pregunta o tienes la más mínima duda, ponte en contacto directo con el Equip",
"seguidores": 3200000,
"pais": "US",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Eze Martínez",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "AR",
"web": "https://www.youtube.com/channel/UCOWFKaCN-rzmYk502JFWnqg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCOWFKaCN-rzmYk502JFWnqg",
"instagram": "https://www.instagram.com/eze.martinez.1/",
"instagram_handle": "@eze.martinez.1",
"tiktok": "https://www.tiktok.com/@eze.martinez.1",
"tiktok_handle": "@eze.martinez.1"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 70,
"problemas": [
"2,140,000 subs",
"outlier 473",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 70/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 2140000,
"outlier": 473,
"fit": 70,
"bio": "Ingeniero y divulgador científico 💡\n\nSoy Ingeniero en Informática, me apasiona la ciencia y la ingeniería y te vengo a mostrar curiosidades que me hubiera gustado contarle al Eze del pasado.\n",
"seguidores": 2140000,
"pais": "AR",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Platzi",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UC55-mxUj5Nj3niXFReG44OQ",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UC55-mxUj5Nj3niXFReG44OQ",
"instagram": "https://www.instagram.com/platzi/",
"instagram_handle": "@platzi",
"tiktok": "https://www.tiktok.com/@platzi",
"tiktok_handle": "@platzi",
"twitter": "https://twitter.com/platzi",
"facebook": "https://facebook.com/platzi"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 69,
"problemas": [
"1,940,000 subs",
"outlier 1159",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 69/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 1940000,
"outlier": 1159,
"fit": 69,
"bio": "Únete al Reto AI Academy de junio y crea proyectos completos de agentes, apps, automatizaciones y más 👇\n",
"seguidores": 1940000,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-07-04",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Pavo Gómez Orea",
"fuente": "youtube",
"categoria": "YouTuber · productividad",
"ciudad": "MX",
"web": "https://www.youtube.com/channel/UCWHNHhViEkii3RHIwIygiZg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCWHNHhViEkii3RHIwIygiZg",
"instagram": "https://www.instagram.com/pavogomezorea/",
"instagram_handle": "@pavogomezorea",
"tiktok": "https://www.tiktok.com/@pavogomezorea",
"tiktok_handle": "@pavogomezorea",
"facebook": "https://facebook.com/pavogo"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 69,
"problemas": [
"94,100 subs",
"outlier 167",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 69/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 94100,
"outlier": 167,
"fit": 69,
"bio": "Soy Empresario Digital, lanzador y 🚀 Director de GO Launch. 🇲🇽\n\n👋 Creo para que logres alcanzar nuevos hábitos, potenciar tu marca personal, generar una reputación digital, libros, marketing, ventas y llevar al siguiente nivel tu productividad.  \n\n¡Suscríbete y construyamos una vida épica!\n",
"seguidores": 94100,
"pais": "MX",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "CenteIA Education",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCsDXXCoXaS-wO1Wnnt_LM3A",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCsDXXCoXaS-wO1Wnnt_LM3A",
"instagram": "https://www.instagram.com/centeia.education/",
"instagram_handle": "@centeia.education"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 68,
"problemas": [
"127,000 subs",
"outlier 279",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 68/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 127000,
"outlier": 279,
"fit": 68,
"bio": "CenteIA Education es el canal para profesionales que quieren usar la Inteligencia Artificial para trabajar mejor, ser más productivos y no quedarse atrás.\n\n⬇⬇ Clases semanales gratuitas en directo ⬇⬇\n https://rebrand.ly/yt-centeia-lm-directo \n\nAquí no hablamos de teoría ni de modas.\n\nTe enseñamos a aplicar la IA de forma práctica, aunque no tengas perfil técnico, para ahorrar tiempo, automatizar t",
"seguidores": 127000,
"pais": "ES",
"enlaces": [
"https://rebrand.ly/yt-centeia-lm-directo"
],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "DonebyLaura",
"fuente": "youtube",
"categoria": "YouTuber · inteligencia artificial para negocios",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UC1m55IoeEf7LKC9s68PDHDg",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UC1m55IoeEf7LKC9s68PDHDg",
"instagram": "https://www.instagram.com/_donebylaura/",
"instagram_handle": "@_donebylaura"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 68,
"problemas": [
"304,000 subs",
"outlier 397",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 68/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 304000,
"outlier": 397,
"fit": 68,
"bio": "Simplemente... me gusta hacer vídeos\n",
"seguidores": 304000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-06-30",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Cyberclick • Marketing Digital",
"fuente": "youtube",
"categoria": "YouTuber · marketing digital",
"ciudad": "ES",
"web": "https://www.youtube.com/channel/UCYXY3S2P7nyjniPPfhNvebw",
"telefono": "",
"email": "",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCYXY3S2P7nyjniPPfhNvebw",
"instagram": "https://www.instagram.com/cyberclicknet/",
"instagram_handle": "@cyberclicknet",
"twitter": "https://twitter.com/cyberclicknet",
"facebook": "https://facebook.com/cyberclicknet",
"linkedin": "https://www.linkedin.com/company/cyberclicknet/"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 67,
"problemas": [
"413,000 subs",
"outlier 9996",
"sin email publico (escribir por el canal)"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 67/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 413000,
"outlier": 9996,
"fit": 67,
"bio": "Cyberclick es una empresa tecnológica especializada en marketing digital y ventas, con más de 25 años de experiencia en el desarrollo y optimización de estrategias orientadas a resultados. Trabajamos en equipos multidisciplinares y altamente especializados en campos como Paid Media, Inbound Marketing, Video Marketing, Social Media, Influencer Marketing, Data Science y Data Analytics, Ecommerce, Ma",
"seguidores": 413000,
"pais": "ES",
"enlaces": [],
"ultima_pub": "2026-07-06",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
},
{
"nombre": "Mark Tilbury",
"fuente": "youtube",
"categoria": "YouTuber · finanzas personales",
"ciudad": "GB",
"web": "https://www.youtube.com/channel/UCxgAuX3XZROujMmGphN_scA",
"telefono": "",
"email": "mark@marktilbury.com",
"direccion": "",
"maps_url": "",
"lat": null,
"lng": null,
"redes": {
"youtube": "https://www.youtube.com/channel/UCxgAuX3XZROujMmGphN_scA",
"instagram": "https://www.instagram.com/marktilbury/",
"instagram_handle": "@marktilbury",
"tiktok": "https://www.tiktok.com/@marktilbury",
"tiktok_handle": "@marktilbury",
"twitter": "https://twitter.com/marktilbury",
"facebook": "https://facebook.com/RealMarkTilbury"
},
"tiene_web": false,
"https": false,
"responsive": false,
"seo": {},
"señales": {},
"nivel_digital": "",
"score": 62,
"problemas": [
"8,610,000 subs",
"outlier 97",
"email publico"
],
"encaja": true,
"mensaje": "",
"motivo": "Fit 62/100 como embajador (nicho + traccion + tamano).",
"canal": "youtube",
"tipo": "creador",
"subs": 8610000,
"outlier": 97,
"fit": 62,
"bio": "Hey, it's Mark. This is my main channel, where I share the lessons I've learned from building a multi-million-dollar business after leaving school at 16 with no qualifications.  Expect practical advice on money, investing, business, and wealth-building.\n\nFor all brand partnerships on this channel contact - mark@marktilbury.com\n",
"seguidores": 8610000,
"pais": "GB",
"enlaces": [],
"ultima_pub": "2026-07-02",
"servicio": "automatizacion",
"createdAt": "2026-07-07",
"sent": false,
"sentAt": "",
"promovido": false,
"estado": "Nuevo"
}
];
